### ISSUE TITLE
CRX で Chrome にインストールできない

### ISSUE THREAD

**Issue by og24715** [hira777/dmm-history#1]
すばらしい拡張機能をありがとうございます。

README のとおり .crx を chrome://extensions の画面へドラッグアンドドロップしてインストールを試みましたが下の画像のような表示が出て有効にできませんでした。

![screenshot_20180523210938](https://user-images.githubusercontent.com/8489199/40423460-9fd22e44-5ecd-11e8-8602-0ed4c4179e0b.png)

詳細を表示すると、下のリンクへ案内されます。
[Chrome によって無効にされた拡張機能 \- Chrome ウェブストア ヘルプ](https://support.google.com/chrome_webstore/answer/2811969?visit_id=1-636626735186866530-968454178&p=ui_remove_non_cws_extensions&hl=ja&rd=2)

Chrome Web Store経由しない拡張機能のインストールは今回が初めてで、以前にこの症状が出ていたかどうかわかりません。
無知で申し訳ありませんが、何かご存知でしたらご助力頂けますと幸いです。

**Comment by hira777** [comment]
@og24715 ご連絡ありがとうございます。確認しますので少々お待ちいただけますか🙇

**Comment by hira777** [comment]
@og24715 いくつかの環境（Mac、Chrome最新版）で試したのですが、再現しなかったです😢。OSやChromeのバージョン、もしくはChrome設定などが原因かもしれませんが、早期の原因特定が困難のため、お手数ですが以下のインストール方法で試していただけますか🙇。

1. [chrome.zip](https://github.com/hira777/dmm-history/releases/download/v1.0.1/chrome.zip)（この拡張のファイルです）をダウンロードし、任意の場所で解凍
1. Chromeの拡張機能ページを開き、画面上にある「デベロッパーモード」にチェックを入れる。
1. 「パッケージ化されていない拡張機能を読み込む」をクリックし、先ほど解凍した`chrome`ディレクトリを選択する。

以下はデスクトップに解凍した`chrome`ディレクトリを選択した例になります。

![install](https://user-images.githubusercontent.com/3727873/40571465-3f035c1a-60d4-11e8-9950-93da1455661b.gif)

**Comment by og24715** [comment]
@hira777 原因究明にお手間取らせて申し訳ありませんでした。
MacOS Sierra 10.12.6, Chrome 66 では .crx をインストールして有効にすることが出来ました。
Windows 10 Home 1709,  Chrome 66 では有効にする事ができませんでした。

ありがとうございます。
Windows では上の .zip を使わせていただいきます。

**Comment by sasaplus1** [comment]
WindowsのChromeで拡張機能がインストールできないのはChrome 33以降の制限が原因ではないでしょうか。

- [重要：Chrome 拡張機能についてのお知らせ](https://productforums.google.com/forum/#!topic/chrome-ja/7qSACiy8EtY)

> **Chrome 33（次の Chrome の安定版）より、Windows 対応の拡張機能は全て Chrome ウェブストア上にホストされていなければならない**

- [Protecting Windows users from malicious extensions](https://blog.chromium.org/2013/11/protecting-windows-users-from-malicious.html)
- [悪意ある Chrome 拡張機能からユーザーを守るために Chrome ウェブストアでホスティングしましょう](https://developers-jp.googleblog.com/2014/03/chrome-chrome.html)

---

（[pageinfo.crx](https://github.com/tsukurite/pageinfo.crx)の開発で全く同様の事態になったことがあります）

**Comment by og24715** [comment]
@sasaplus1 わー。
そのとおりのようですね。自力ではこの情報にたどり着けませんでした。
ありがとうございます。

**Comment by hira777** [comment]
@sasaplus1 あー、そうだったんすね!ご共有ありがとうございます!
